### ISSUE TITLE
Bug report (gertjan 25 nov windows)

### ISSUE THREAD

**Issue by rluijk** [Synestheticminds/UnderdogCowboy#4]
Pre Release -- Early Access Version... Nov-Dec 2024
If you do not have my Whatsapp, DM on linked-in for issues that need solving: https://www.linkedin.com/in/reneluijk/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\gertj\AppData\Local\Programs\Python\Python312\Scripts\uc-agent-flow.exe\_main_.py", line 4, in <module>
  File "C:\Users\gertj\AppData\Local\Programs\Python\Python312\Lib\site-packages\underdogcowboy\_init_.py", line 80, in <module>
    from .core.uc_agent_communicator import UCAgentCommunicator
  File "C:\Users\gertj\AppData\Local\Programs\Python\Python312\Lib\site-packages\underdogcowboy\core\uc_agent_communicator.py", line 56, in <module>
    from uccli import AgentCommunicator
ImportError: cannot import name 'AgentCommunicator' from 'uccli' (unknown location)

C:\Windows\System32>pip show uccli
WARNING: Package(s) not found: uccli

C:\Windows\System32>pip install uccli
ERROR: Could not find a version that satisfies the requirement uccli (from versions: none)
ERROR: No matching distribution found for uccli

**Comment by rluijk** [comment]
most likely this is about wrong inclusion of the separate library for states. 
I am working on bumbing a minor release 0.1.14.1 for a potential fix. 
Pull request is in. #5
